name: Create EC2 Instance on Push

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  create-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your AWS region

    - name: Launch EC2 instance
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ami-0c55b159cbfafe1f0 \  # Replace with your region's AMI
          --count 1 \
          --instance-type t2.micro \
          --key-name your-key-name \         # Replace with your key pair
          --security-groups your-sg-name \   # Replace with your security group
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=GitHub-EC2}]' \
          --query 'Instances[0].InstanceId' \
          --output text)

        echo "Launched EC2 Instance ID: $INSTANCE_ID"

        aws ec2 wait instance-running --instance-ids $INSTANCE_ID

        PUBLIC_IP=$(aws ec2 describe-instances \
          --instance-ids $INSTANCE_ID \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)

        echo "EC2 Public IP: $PUBLIC_IP"
