name: Deploy EC2 Instance

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Launch EC2 instance
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ami-0953476d60561c955 \  # Replace with your region's AMI
          --count 1 \
          --instance-type t2.micro \
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=GitHub-EC2}]' \
          --query 'Instances[0].InstanceId' \
          --output text)

        echo "Launched EC2 Instance ID: $INSTANCE_ID"
